spring:
  datasource:
    url: jdbc:postgresql://postgres:5432/ivura
    username: postgres
    password: postgres

minio:
  url: http://minio:9000
  access-key: minioadmin
  secret-key: minioadmin123
  bucket: ivura-files
