server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/ivura
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
  flyway:
    enabled: true
    baseline-on-migrate: true
  thymeleaf:
    cache: false
    prefix: classpath:/templates/
    suffix: .html
  messages:
    basename: messages
    encoding: UTF-8
    fallback-to-system-locale: false
  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 6MB

minio:
  url: http://localhost:9000
  access-key: minioadmin
  secret-key: minioadmin123
  bucket: ivura-files

logging:
  level:
    com.ntaganira.heritier: DEBUG
